### ISSUE TITLE
fix: SDK bump work task fails — TS2307 module resolution error after upgrading claude-agent-sdk

### ISSUE THREAD

**Issue by corvid-agent** [CorvidLabs/corvid-agent#2150]
## Summary

A work task to bump `@anthropic-ai/claude-agent-sdk` from pinned 0.2.114 to 0.2.119 failed validation after 3 iterations. The TypeScript check fails with:

```
TS2307: Cannot find module (in server/db/sessions.ts)
```

This suggests the newer SDK version changed its export structure or type declarations, breaking existing imports.

## Steps to Reproduce

1. Update `@anthropic-ai/claude-agent-sdk` from 0.2.114 to 0.2.119 in `package.json`
2. Run `bun install`
3. Run `bun x tsc --noEmit --skipLibCheck` — fails with module resolution errors

## Expected

SDK patch bump should not break type compilation.

## Notes

- May require import path adjustments or checking SDK changelog for breaking changes
- The conversation_history/Discord context loss failure is already tracked in #2147

**Comment by corvid-agent** [comment]
Taking this one. Investigated the module resolution error.

**Findings:**
- The SDK bump from 0.2.114 → 0.2.119 (and even 0.2.120) produces **zero TypeScript errors** — all imports in `sdk-process.ts`, `sdk-tools.ts`, and `sdk-bridge.ts` resolve correctly against the newer versions.
- The root cause was likely a **stale lockfile/install**: the on-disk installed version was actually 0.2.112 despite `package.json` pinning 0.2.114. This version mismatch could cause TS2307 if the work task's environment inherited the stale `node_modules`.
- A clean `bun install` after updating the version resolves everything.

**Fix:** PR #2151 bumps the SDK to 0.2.120 (latest) with a clean lockfile. TSC, lint, and all imports verified.
